name: CI
on: [pull_request]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Install tools
        run: |
          mkdir -p $HOME/bin 
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.18.0
          echo ::add-path::$HOME/bin

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Docker Compose Up
        run: docker-compose up -d
    
      - name: Check running containers
        run: docker ps -a

      - name: Running CI
        run: make ci

      - name: Upload code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CodeCovToken }}
        run: |
          bash <(curl -s https://codecov.io/bash)
        

